title: InsideOut Blog
description: A personal blog exploring thoughts, ideas, and everything in between.
url: "https://bita-c.github.io"
baseurl: "/insideout-blog"

#theme: minima
remote_theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-feed

sass:
  quiet_deps: true

nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/